### ISSUE TITLE
Problem with the Extended Example from the Getting Started section

### ISSUE THREAD

**Issue by soulimane-mammar** [cbjartli/Gjs-Tutorial#3]
Hi,
I can't run the following code
`#!/usr/bin/gjs

const Gtk = imports.gi.Gtk;
const Lang = imports.lang;

Gtk.init(null);

class MyWindow extends Gtk.Window {
    constructor() {
        super({ title: "Hello World" });
        this.button = new Gtk.Button({ label: "Click here" });
        this.button.connect("clicked", MyWindow.onButtonClicked);
        this.add(this.button);
    }

    static onButtonClicked() {
        print("Hello World");
    }   
}
GObject.registerClass(MyClass);

let win = new MyWindow();
win.connect("delete-event", Gtk.main_quit);
win.show_all();
Gtk.main();`

The lang module imported but never used
MyClass refrenced but never used
when running gjs is complaining about the ES6 syntax (class definition)

**Comment by KristjanESPERANTO** [comment]
I also can't run this example (version from 2018-02-15):

`kristjan@debian:~$ gjs extended_example.js`
`(gjs:30424): Gjs-CRITICAL **: JS ERROR: SyntaxError: class is a reserved identifier @ extended_example.js:7`
`JS_EvaluateScript() failed`

The simple_example.js works fine.

My system:
- gjs version: 1.46.0-1+b2
- debian version: 9.7

**Comment by ptomato** [comment]
That's a really old GJS version that doesn't support classes.

**Comment by KristjanESPERANTO** [comment]
Okay, that's a simple explanation. A hint in the tutorial might be helpful, which version is needed at least for the tutorial.

**Comment by ptomato** [comment]
I don't think the maintainer of this tutorial is working on it anymore, maybe you could make a pull request for that in case they come back and merge the pull requests?

**Comment by KristjanESPERANTO** [comment]
Thank you! :-) I created a pull request.

**Comment by cbjartli** [comment]
Thank you so much for your input, and sorry for being on hiatus! @ptomato, @KristjanESPERANTO and others, I'll have a look at this ASAP.

**Comment by ptomato** [comment]
Awesome, thanks @cbjartli, good to see you again! :smile:
